apiVersion: v1
kind: Secret
metadata:
  name: kwazo
type: Opaque
data:
  MYSQLDB_HOST: a3dhem8ubXlzcWwuZGF0YWJhc2UuYXp1cmUuY29t
  MYSQLDB_USER: a3dhem8=
  MYSQLDB_PASSWORD: QWRtaW5pc3RyYXRvcjE=
  MYSQLDB_PORT: MzMwNg==
  AMQP_URL: YW1xcHM6Ly93bXBraW55czptQjcyMHpuUnNPN0EyV25tM2I3MElTd0ZMVmt6V0ZTeUBnb29zZS5ybXEyLmNsb3VkYW1xcC5jb20vd21wa2lueXM=
  JWT_SECRET: S3dhem8tc2VjcmV0LWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: kwazo-user-database
type: Opaque
data:
  MYSQLDB_DATABASE: dXNlcnNlcnZpY2U=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwazo-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwazo-user
  template:
    metadata:
      labels:
        app: kwazo-user
        version: IMAGE_LABEL
    spec:
      containers:
      - name: kwazo-user
        image: ACR_URL/kwazo-user:IMAGE_LABEL         
        envFrom:
        - secretRef:
            name: kwazo-user-database
        - secretRef:
            name: kwazo
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: kwazo-user-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: kwazo-user
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kwazo-ingress
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: kwazo-user-service
            port:
              number: 80
      - path: /posts
        pathType: Prefix
        backend:
          service:
            name: kwazo-post-service
            port:
              number: 80
      - path: /comment
        pathType: Prefix
        backend:
          service:
            name: kwazo-comment-service
            port:
              number: 80
              
